### ISSUE TITLE
Tests broken since release 3.0.0

### ISSUE THREAD

**Issue by vemonet** [NCATSTranslator/reasoner-validator#40]
**Describe the bug**

Before release 3.0.0 we were using the `reasoner-validator`  to validate the output of our TRAPI APIs

But since release 3.0.0 we are getting the following error:

```python
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/production/test_production_api.py:7: in <module>
    from reasoner_validator import validate
/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/reasoner_validator/__init__.py:4: in <module>
    from reasoner_validator.biolink import (
/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/reasoner_validator/biolink/__init__.py:14: in <module>
    from reasoner_validator.sri.util import is_curie
E   ModuleNotFoundError: No module named 'reasoner_validator.sri'
```

Here is the description of release 3.0.0. It does not seems like any breaking changes have been introduced according to this description (why moving to 3.0.0 in this case btw?)

> Reports validation status messages - error, warning and information - using a parameterized coded messages (see the codes.yaml file in the project). Some validation previously tagged as 'error' are now 'warning' or 'information' messages.

**To Reproduce**
Code to reproduce the behavior:

```python
from reasoner_validator import validate
TRAPI_VERSION_TEST: str = "1.2.0"
assert validate(trapi_results['message'], "Message", TRAPI_VERSION_TEST) == None
```

It can't be more simple, so I have hard time to see how I can trigger an import issue here

cf. https://github.com/MaastrichtU-IDS/translator-openpredict/blob/master/tests/production/test_production_api.py#L42

**Expected behavior**
It should have worked like it was working before
Or there should be a disclaimer in the Release notes for 3.0.0 explaining which changes I need to make to have it working

**Comment by RichardBruskiewich** [comment]
Hi @vemonet, sorry about your difficulties. 

Yes, the 3.0 is not backwards compatible with the 2.*.* releases previously published since the software library API has changed. In fact, the code snippet above is actually incorrect (in the new release).  The changes were made in response for emerging Translator testing scope and use, especially, TRAPI 1.3 and Biolink 3.*. 

As you know, the pace of change on both fronts has been very fast.   The missing module error is surprising, though: I wonder if there is a need to refresh local (venv?) Python dependencies for the software?  If you need to move forward right away, the unit tests should all pass and show the proper (new) design patterns for using the library.

For the short term, please see if you can commit to stay with the previous **reasoner-validator** release  (2.2.14)  awhile longer (https://github.com/NCATSTranslator/reasoner-validator/releases/tag/v2.2.14) while a few rough edges and the documentation are fixed. Alas, as you correctly noted, the documentation for this was not yet fully regenerated (at the top of the TODO list right now).

Again, sorry... We'll iterate quickly on this over the next few days to resolve these concerns.

**Comment by RichardBruskiewich** [comment]
Concerns fully addressed by release https://github.com/NCATSTranslator/reasoner-validator/releases/tag/v3.1.4. Note that some spurious validation errors with respect to non_canonical predicates may be observed. This defect is a consequence of the model changes in Biolink Model Toolkit upgrading from Biolink Model 2.4.8 to 3.0.0 (outside the control of the reasoner-validator package itself).
