### ISSUE TITLE
check_compliance_of_trapi_response() only works with Message not Response

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#41]
Moving from reasoner-validator 2.2.14 to 3.1.0 with some issues.

Version 3.1 seems to work with this:
```
from reasoner_validator import TRAPIResponseValidator
    validator = TRAPIResponseValidator(trapi_version=trapi_version, biolink_version=biolink_version, sources=None, strict_validation=True)
    validator.check_compliance_of_trapi_response(message=envelope['message'])
    validation_result = validator.get_messages()
```

And seems to work pretty well. The most startling thing is that even though the class and main method are named as if they are designed to validate a TRAPI Response object, the check_compliance_of_trapi_response() method only seems to work when passed a TRAPI Message object (child of Response). Does not work when passed a Response object. I think it should!

**Comment by RichardBruskiewich** [comment]
This issue substantially resolved by commit https://github.com/NCATSTranslator/reasoner-validator/commit/0e5ed3a402c800ba72a4d073e9049d348f50dc4f.

There are some additional TRAPI workflow validation measure which could be taken but we defer these to another day (and issue: https://github.com/NCATSTranslator/reasoner-validator/issues/57) but consider this issue otherwise resolved (for now).
