### ISSUE TITLE
error code with made-up predicate

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#44]
reasoner_validator 3.1 with TRAPI version 1.3.0 and biolink_version 2.2.11, I see this:

```
  "errors": [
.......
    {
      "context": "Query Graph n00--['biolink:has_normalized_google_distance_with']->n01 Predicate",
      "name": "biolink:has_normalized_google_distance_with",
      "code": "error.unknown"
    }
  ]
```

I suppose the problem is that biolink:has_normalized_google_distance_with is something that we made up and isn't real.

First, should "code" be something more clarifying that "error.unknown"?

Second, What should we be using instead of biolink:has_normalized_google_distance_with?

**Comment by RichardBruskiewich** [comment]
The `error.unknown` code actually corresponds to [an error message template](https://github.com/NCATSTranslator/reasoner-validator/blob/master/reasoner_validator/codes.yaml#L60) which is more informative once it is decoded by software. 

That said, in this instance, how would we distinguish between predicates that _used to be found_ in the Biolink Model, but were deprecated then removed in a major release, versus the case of a made up predicate? 

Does it matter? Or does it suffice to state that the term (in this case, a predicate) is simply unknown within the target version (2.2.11) of the Biolink Model?

**Comment by edeutsch** [comment]
`error.unknown` sounds to me like the validator is lost in a state of confusion and something bad happened but it is not known what bad thing happened.

"predicate is unknown within the target version (2.2.11) of the Biolink Model"
sounds like a great error message that is very  informative.

**Comment by edeutsch** [comment]
And we never addressed this:

> Second, What should we be using instead of biolink:has_normalized_google_distance_with?

Do we need to ask @sierra-moxon ?

**Comment by RichardBruskiewich** [comment]
> And we never addressed this:
> 
> > Second, What should we be using instead of biolink:has_normalized_google_distance_with?
> 
> Do we need to ask @sierra-moxon ?

Yes, ask the High Priestess of Biolink about this, or maybe - if your colleagues and you consider it an essential distinct predicate, issue an issue (or, if ambitious, a PR) directly to the Biolink Model repository.

**Comment by RichardBruskiewich** [comment]
> `error.unknown` sounds to me like the validator is lost in a state of confusion and something bad happened but it is not known what bad thing happened.
> 
> "predicate is unknown within the target version (2.2.11) of the Biolink Model" sounds like a great error message that is very informative.

Agreed. This code is a bit opaque. I'll make it a bit more informative: it should read more precisely as something like **`error.biolink.element.unknown`**.  

That said, this code is actually associated with a [code message template](https://github.com/NCATSTranslator/reasoner-validator/blob/master/reasoner_validator/codes.yaml) within which further context is injected (this is in the dictionary reported back with the code).

On the issue of Biolink Model release, the model version context should now DRYly globally reported in the error report and not embedded inside messages now, since all validations of a given resource validate against the same Biolink Model version.
