### ISSUE TITLE
Accept version as a parameter for old version support

### ISSUE THREAD

**Issue by shanelanan** [NCATSTranslator/reasoner-validator#7]
Requesting a feature to accept version as a parameter when bumping to latest version.  For example, when you bump your package to 1.1.X, then it would accept 1.1.X, as well as all the older versions to validate as a parameter.

PyYaml update creates 2 different dependencies in version 1.0.X and 1.1.X.

This way, we could install the latest version of your package, but then to validate my 0.9, 1.0 old versions, I would just need to tell it what version.

**Comment by patrickkwang** [comment]
Yeah, handling versions here is tricky.
There are a couple reasons we chose not to fix each release to a specific TRAPI version.

1. This keeps the package as lightweight as possible. We don't have to include every historical TRAPI spec or GET them at run time (reasoner-validator works without an internet connection).
2. The TRAPI components sometimes actually change names between versions. Since our functions are named after the TRAPI components, it seems strange to allow specification of the version with each function call.

Now, if we were to restructure our API a bit, these objections could carry less weight. Something like jsonschema's [IValidator interface](https://python-jsonschema.readthedocs.io/en/stable/validate/#the-validator-interface) might would be better.

**Comment by shanelanan** [comment]
Thanks Patrick for the feedback.

Regarding item 1, the package you build is already super duper light weight, and you've released on a view versions which mainly only change the .yml file schema.   Since your function signatures are all dynamic anyways, then it seems feasible to just accept schema_version="something" as an argument to the validation.

Regarding item 2, same point about dynamic function signatures.  Our intellisense can't pick it up, anyway.  Seems like this would work if the validation object and the schema are both passed, then it would solve both of those problems.

For example, something like:
`
reasoner_validator.validate_Response(myResponseObject)
`
would become
`
reasoner_validator.validate(validationObject=myResponseObject, validationType="Response", validationSchema="1.0.2") 
`
Right now, my intellisense doesn't help me at all as you can see here:
![image](https://user-images.githubusercontent.com/44124270/117348294-0948b300-ae78-11eb-9093-b56389acd9f3.png)

**Comment by patrickkwang** [comment]
All good points. And avoiding hitting the internet is kinda silly for 1) any PyPI package and 2) especially one meant for validating REST API payloads.

It's a bummer that intellisense doesn't work. What does work with the dynamic function generation is the sphinx autodoc. I was having a bit of fun there, but a well-documented bad API is still a bad API.

So we're talking about a substantial change, but it should make the package more usable and actually easier to maintain in the future. I'll make a 2.0 branch.

**Comment by shanelanan** [comment]
For our stack, we are versioning our api through the router like /v0.9/ /v1.0/ and /v1.1.

So its all the same source code, infrastructure, cicd, container, etc.  So we cannot install 2 versions of the same package (your package).

So we have resorted to copy your source code for reasoner_validator 1.0 and pasting it in statically, and then install from github for the latest 1.1.
