### ISSUE TITLE
Reasoner Validator yielding incorrect errors for primary_knowledge_source in TRAPI 1.4

### ISSUE THREAD

**Issue by CaseyTa** [NCATSTranslator/reasoner-validator#70]
**Describe the bug**
When trying to validate our TRAPI 1.4 messages, we're getting two errors:  
`error.knowledge_graph.edge.provenance.missing_primary`   
`error.knowledge_graph.edge.attribute.missing`

I *think* we have the new RetrievalSource modeled correctly for TRAPI 1.4, so I'm guessing reasoner validator is still looking in attributes for the primary_knowledge_source. 

On a related note, KG Edge attributes are not required and are nullable in TRAPI 1.3 and 1.4, but `error.knowledge_graph.edge.attribute.missing` implies attributes are required. I assume this is related to the requirement for primary_knowledge_source, and so this error code may not be applicable to 1.4. 

**To Reproduce**
Validating TRAPI response against 1.4.0-beta. Can try the attached COHD response. 

[cohd_trapi_1.4.txt](https://github.com/NCATSTranslator/reasoner-validator/files/11066138/cohd_trapi_1.4.txt)

**Comment by RichardBruskiewich** [comment]
The [latest release](https://github.com/NCATSTranslator/reasoner-validator/releases/tag/v3.4.15) doesn't report missing provenance in TRAPI 1.4.0 from attributes but rather, now validates provenance inside the **`RetrievalSource`.**.  I don't think attributes should be reported missing either.

Hopefully the above issues are resolved (in the latest **reasoner-validator** release). @CaseyTa let me know otherwise, in case I missed something along the way.

**Comment by CaseyTa** [comment]
Tested on reasoner-validator 3.4.15 and all looks good on our end. Thanks, @RichardBruskiewich!
