### ISSUE TITLE
dependence issue

### ISSUE THREAD

**Issue by gloriachin** [NCATSTranslator/reasoner-validator#71]
**Describe the bug**
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

**Comment by RichardBruskiewich** [comment]
@gloriachin: Don't use pip; use poetry to manage dependencies.

**Comment by RichardBruskiewich** [comment]
Not a defect with the code base, but using old copy of the code or not using poetry for dependency management. Closing this issue (unless proven otherwise)

**Comment by RichardBruskiewich** [comment]
@gloriachin I revisited the main docs at https://ncatstranslator.github.io/reasoner-validator/ and realized that some of them were slightly out-of-date. I removed spurious mentions of pip except for pypi.org installation, for which I think it is still valid. Otherwise, the recommendation is for poetry installation.
