### ISSUE TITLE
Should we distinguish validation between critical versus simple errors

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/reasoner-validator#82]
A philosophical point for the Consortium: should validation "error" codes be considered "critical" show stoppers for a given TRAPI query outcome - i.e. a full query failure - or rather, say, just a strong admonition to repair the semantics?

One almost has the sense here that we could have two levels of errors: "regular" (non-show-stopping-but- important) errors, versus critical ("show stopping") errors. I now that this is splitting hairs a little bit but I guess, it is worth considering if this is the case, to facilitate triage of remedial actions.

A non-show stopping error may be purely semantic (e.g. **`attribute_type_id`** CURIE should preferably be from Biolink, but isn't?) whereas, a structural defect (e.g. TRAPI schema validation error) is certainly a show stopper for TRAPI consumption.

**Comment by edeutsch** [comment]
I agree, I think this would be quite useful. Fatal errors would be schema violations, references to nodes that don't exist, etc. while software errors might be certain values that current policy has as inappropriate, although our policies might change based on various use cases.

**Comment by RichardBruskiewich** [comment]
I'm wondering how best to tag these two categories of errors in a meaningful discerning manner?

"fatal_error" ("critical_error"?) versus "error" (is this just a "warning") versus "warning" ("advisory")

**Comment by edeutsch** [comment]
Suggested description of the difference:
 
fatal error: an error that can be and should be correctable as soon as possible because it probably will cause UIs to fail to render the Response properly
 
error: an error that might not be easily correctable without further input from the consortium, but should be addressed rapidly by the consortium because it likely has a substantial impact on displaying information to users
 
warning: a problem that indicates non-conformance to a stated or implicit rule, but may not be easily solved without substantial effort by the consortium, and is not considered high priority since it does not substantially impact the ability to show users complete results.

**Comment by RichardBruskiewich** [comment]
Initially resolved by [release 3.6.0 ](https://github.com/NCATSTranslator/reasoner-validator/releases/tag/v3.6.0).
The full list of error validation in [codes.yaml](https://github.com/NCATSTranslator/reasoner-validator/blob/v3.6.0/reasoner_validator/codes.yaml) need to be reviewed for additional messages to promote to 'critical'.
